### ISSUE TITLE
1.0.2-dev-2 转发进QQ的推文无图片

### ISSUE THREAD

**Issue by XinLinYu** [cssxsh/twitter-helper#11]
推特原文：https://twitter.com/pj_sekai/status/1412607912048926720
转发内容：
![image](https://user-images.githubusercontent.com/48984235/124695605-19cbe700-df16-11eb-9b9a-daadca808282.png)

控制台内容：
![image](https://user-images.githubusercontent.com/48984235/124695732-61527300-df16-11eb-9fe7-920b3fcc539a.png)

yml文件配置：
![image](https://user-images.githubusercontent.com/48984235/124695658-3536f200-df16-11eb-997f-f0a5d796ae81.png)

**Comment by cssxsh** [comment]
你可以先试试 https://github.com/cssxsh/twitter-helper/releases/tag/v1.0.2-dev-2
